### ISSUE TITLE
Deploy app to Heroku

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#1]
# Tasks
- [x] Create Heroku app
- [x] Push repo to heroku remote
- [x] Set Heroku environment variables
