### ISSUE TITLE
Add Google OAuth to app

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#10]
# Tasks
-  [x] Create new app on Google Cloud Platform
- [x] Create new credentials for app
- [x] Copy client id and client secret to .env variables
- [x] Update passport files  and routes to support Google OAuth
- [x] Add "Log in with Google" button to LoginPage.js and wire button
- [x] Test to verify that Google OAuth works properly. It should add a new user to the database.
