### ISSUE TITLE
Testing #56: Badge system

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#14]
This issue writes tests for badge system (#56) .

- [ ] #101
- [ ] #102
- [ ] #103
- [ ] #104
- [ ] #105
- [ ] #106
- [ ] #107

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for badge system UI
- [ ] Use Postman to write tests for RESTful API to support badge system UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
