### ISSUE TITLE
As a user, I want to earn badges for app achievements so that I am motivated to do better

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#15]
# Pre-Coding tasks
1. What kind of badge system do we want?
  - [ ] Each category has its own symbol, color determines degree?
  - [ ] (1) set of symbols that is used across all categories, each symbol represents a higher degree?
  - [ ] Look into other speedgolf apps and see what has been used before?
  - [ ] Something else entirely?
  * How many degrees do we want?
  * What colors do we want to use?
  * What symbols do we want to use?
 
2. Look into Speedgolf stats to determine what ranges to use for:
* `Number of Rounds` played badges
* `Round Time` badges
* `Strokes` badges
* `Frequency` or `Streaks` badges

# Acceptance Criteria

In "Rounds" mode:
- [ ] Users see a large congratulatory message and badge when they log rounds that unlock the badge.
- [ ] An "Earn badges" link can be clicked to find out more information on available badges.
- [ ] Users can earn badges based on the number of rounds they play (10, 20, 30, etc.)
- [ ] Users can earn badges based on their round time
- [ ] Users can earn badges based on their golf strokes
- [ ] Users can earn badges for frequency of play or streaks

In "Feed" mode:
- [ ] Icons representing users' badges are displayed alongside the users whenever they appear in the feed. 
- [ ] A tooltip explains the badge in more detail.

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
