### ISSUE TITLE
Testing #54: As a user, I can log a round "live" through a speech interface...

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#16]
This issue writes tests for speech UI for logging rounds (#54) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for speech round logging UI
- [ ] Use Postman to write tests for RESTful API to support speech round logging UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
