### ISSUE TITLE
As a user, I can log a round "live" through a speech interface, so that I can capture detailed data on my round unobtrusively

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#17]
# Acceptance Criteria
- [ ] When user clicks "Log Round," they are given choices "Track Live (Speech)" or "Log Previously Played"
- [ ] If user chooses "Track Live (Speech)" they are taken to the Live Tracking Speech UI.
- [ ] User says "start" to start round
- [ ] User says "pause" to pause timing a round.
- [ ] User says "cancel" to cancel previous voice command.
- [ ] User says "In x" to indicate a hole is finished, where x is the strokes taken on the hole.
- [ ] Hole automatically advances to next hole when current hole is finished.
- [ ] User says "Correct hole x score y" to change the number of strokes recorded on hole x to y.
- [ ] User says "Time" to have the app say the current elapsed time for the round
- [ ] User says "Strokes" to have the app say the current elapsed strokes for the round.
- [ ] User says "Distance" to have the app say the current distance (in yards) from the hole.
- [ ] User says "heartrate" to have the app say the user's current heartrate (if available)
- [ ] User says "voice note [note] end voice note" to record a voice note at the current point in the round.
- [ ] User says "terminate" to stop recording the current round and discard it. The app requires that this be confirmed by asking "Are you sure you want to terminate the current round ("Yes" or "no")?

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
