### ISSUE TITLE
Testing #52: As a user, I want to be able to save pictures and videos...

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#18]
This issue writes tests for [issue description] (#52) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for picture/video saving UI
- [ ] Use Postman to write tests for RESTful API to support picture/video UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
