### ISSUE TITLE
As a user, I want to be able to save pictures and videos with my speedgolf rounds so that i can better document my rounds

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#19]
# Acceptance Criteria

In "Rounds" mode:
- [ ] Users should be able to save one or more pictures with a round.
- [ ] Users should be able to mark one of the pictures as the "main" picture for the round.
- [ ] The "main picture for a round should be displayed with each round in the "Rounds" table.
- [ ] Users should be able to save one or more videos with a round.
   - [ ] A video can be a link to a YouTube video
   - [ ] A video can be uploaded to the database (Max size: 100 MB)
...

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
