### ISSUE TITLE
Complete Milestone Report

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#3]
# Tasks
- [x] Compile required statistics for "Communication" section
- [x] Compile retrospective summary
- [x] Compile required links for "Progress" section
- [x] Work with team to compute story point shares for "Progress" section
- [x] Work with team to compile links to test files and animated GIFs for "Testing" section
- [x] Fill in template in README.md for Milestone 0
