### ISSUE TITLE
Testing #36: As as user, I want to visualize my round stats in a graph...

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#34]
This issue writes tests for the round stats graphing feature (#36) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for round stats graphing UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
