### ISSUE TITLE
As a user, I want to visualize my round stats in a graph so that I can gain insight into my speedgolf progress

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#35]
# Acceptance Criteria
From "Rounds" mode tab:
- [ ] Users can toggle between "Table" and "Graph" subtabs
- [ ] Current Rounds table is shown in "Table" subtab
- [ ] Line graph of SGS (y axis) by date (x axis) is shownin "Graph subtab
- [ ] In "Graph" subtab, user can toggle item being graphed on y axis through a radio button:
   - [ ] SGS (default)
   - [ ] Strokes
   - [ ] Time
- [ ] In "Graph" subtab, user can filter the data graphed by course from a dropdown menu with "All courses" (default) and an entry for each golf course the user on which the user has logged a round. 
- [ ] In "Graph" subtab, user filter the data graphed by a specific date window specified through "Begin Date" and "End Date" fields 
...

# Implementation Todos

Front end:

- [ ] Consider leveraging a third party graphing component.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] This user story should not require any back-end database changes. It's all on the front end.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
