### ISSUE TITLE
Testing #25: Asd a user, I want to view and search speedgolf-friendly courses...

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#36]
This issue writes tests for the speedgolf course search/view functionality (#25) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for [feature description] UI
- [ ] Use Postman to write tests for RESTful API to support [feature description] UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
