### ISSUE TITLE
Testing #26: As a user, I want to add and edit speedgolf-friendly courses

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#37]
This issue writes tests for adding/editing speedgolf-friendly courses (#26) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for ad/edit course UI
- [ ] Use Postman to write tests for RESTful API to support add/edit course UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
