### ISSUE TITLE
Testing #27: As a user I want to be able to review courses and view others' reviews...

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#38]
This issue writes tests for the course review user story (#27) .

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for course review UI
- [ ] Use Postman to write tests for RESTful API to support course review UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
