### ISSUE TITLE
Run TPM 2 retrospective meeting

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#39]
# Tasks
- [ ] Run retorspective meeting via Zoom according to instructions provided in class
- [ ] Document results in Milestone report (in README.md file)
- [ ] The following team members participated in the retrospective:
   - [ ] Team member 1
   - [ ] Team member 2
   - [ ] Team member n
