### ISSUE TITLE
Complete TPM 2 Report

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#42]
# Tasks
- [ ] Compile required statistics for "Communication" section
- [ ] Compile retrospective summary
- [ ] Compile required links for "Progress" section
- [ ] Work with team to compute story point shares for "Progress" section
- [ ] Work with team to compile links to test files and animated GIFs for "Testing" section
- [ ] Fill in template in README.md for TPM 2
