### ISSUE TITLE
As a user, I want to be able to review courses and view others' reviews so that I can understand how speedgolf-friendly courses are

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#44]
# Acceptance Criteria
From "Courses" tab in app:
- [ ] Each course in list contains
   - [ ]  an average star rating (out of 5) and clickable link to view reviews (see screenshot)
   - [ ] Number of speedgolf rounds logged on course
   - [ ] Map button (clicking on it brings up course on Google map)
   - [ ] Contact button (clicking on it brings up course contact info -- phone number/email as available)
- [ ] Clicking on "Reviews" link brings up a list of all reviews, sorted from most recent to least recent, with overall stats at top of "Reviews" page:
   - [ ] Speedgolf course ranking (e.g., 1/200)
   - [ ] Speedgolf rounds logged: <number>
   - [ ] Average ratings for "speedgolf friendliness," "golf challenge," "running challenge," and "overall speedgolf experience"
- [ ] "Write Review" floating action button on "Reviews" page brings up modal dialog for adding a review:
     - [ ] Review comments (essay box)
     - [ ]  Speedgolf friendlienss (5 star scale)
     - [ ] Golf challenge (5 star scale)
     - [ ] Running challenge (5 star scale)
     - [ ] Overall speedgolf experience (5 star scale)

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] Update "courses" collection in database with schema for course ratings data 
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
