### ISSUE TITLE
As a user, I want to add and edit speedgolf-friendly courses to the app's course database

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#45]
# Acceptance Criteria
From the "Courses" tab in the app:
- [ ] The "Add Course" floating action button brings up a modal dialog form for adding a course to the courses database
- [ ] Modal dialog form fields:
   - [ ] Course name: As user types in name, search is performed using Google Maps API to identify potential matching courses. Matching courses are presented in autocomplete dropdown. If a course in the dropdown is selected, other form fields autocomplete based on Google Maps DB data.
   - [ ] Address (required -- autocompleted from Google Maps API if possible)
   - [ ] Phone number (optional -- autocompleted from Google Maps API if possible)
   - [ ] Geolocation (optional -- autocoompleted from Google Maps API if possible)
   - [ ] Picture (optional -- a URL can be supplied or picture uploaded)
   - [ ] Add tee (a button that allows the user to add data on a specific tee on the course (e.g., "White")
      - [ ] Name
      - [ ] Golfing yardage
      - [ ] Running yardage
      - [ ] Number of holes
      - [ ] Hole-by-hole stroke pars, golfing yardages, running yardages, time pars (virtual field)
      - [ ] Time pars computed by multiplying time par multipler by the running yardage for a hole 
      - [ ] time par constant (seconds per 100 yards; defaults to 70
      - [ ] Speedgolf record (person's name (or id if they are an app user) minutes, seconds, strokes, and date)
- [ ] Courses displayed in list, with "View/Edit" and "Delete" buttons available for each course
- [ ] "View/Edit" button brings up the modal dialog pre-populated with data. Users can change data and click "Update" to update. 
- [ ] "Delete" button brings up a pop-up "Confirm deletion" modal dialog. user must approve deletion before it occurs.

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:
- [ ] Add "Courses" collection to app database and schema corresponding to the above fields.
- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
