### ISSUE TITLE
As a user, I want to view and search speedgolf-friendly golf courses so that I can be aware of which courses are good for speedgolfing

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#46]
# Acceptance Criteria

From the "Courses" tab in the app:
- [ ] Users see a list of all courses in the app's course database (or the first 100 if more than 100 are present)
- [ ] A search box at the top of the screen allows users to filter courses using a text string. All courses matching the search string are displayed. The courses are updated on every keystroke.
- [ ] Courses are searched based on their name and location.
- [ ] an "x" button to right of search box clears the current filter and redisplays all courses.

# Issue Prerequisites
- #26: Add/edit/delete speedgolf courses 

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
