### ISSUE TITLE
As a user, I want to see an activity feed of my buddies' rounds and posts so that I can connect with them 

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#48]
# Dependencies
Implementing this user story first requires you to implement user story #22 (Buddies mode).

# Acceptance Criteria

From the "Feed" mode tab in the app:
- [ ] Users see a chronological listing of all shared rounds and posts made by them and their buddies, just like a Facebook feed
   - [ ] Example: "ChrisH logged a speedgolf round (124:32 (76 in 48:32) (Date and time)"
   - [ ] User's profile pic included in post.
- [ ] Any round posted on feed is clickable. Clicking on the round brings up (as a modal dialog) a read-only version of "View/Edit" round page corresponding to that round.
- [ ] When logging a round, users have the option of not sharing a round to the feed by clicking a "Keep round private" checkbox on the "Log Round" page
- [ ] Users can "Fist bump" a round through a "Fist bump" button
- [ ] Users can reply/comment on a posted round through a "Write a comment" text box (like Facebook).
- [ ] users can post to their feed through the "Post" floating action button. Posts can include text, pictures and video
- [ ] Users can "like" or reply to any post (including their own) on the feed
- [ ] Users can tag any buddy in a post using the hashtag. Autocompletion for hashtags works (bonus of 1 story pt) 
...

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] Create database schema for feed posts/replies 
- [ ] Add "keepPrivate" boolean to rounds objects in database
- [ ] Additional things that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
