### ISSUE TITLE
Testing #21: Buddies mode

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#49]
This issue writes tests for Buddies mode (#21 )

# To Do
- [ ] Use TestCafe or Playwright to write UI tests for Buddies UI
- [ ] Use Postman to write tests for RESTful API to support Buddies UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
