### ISSUE TITLE
Testing: As a user, I can edit my account and profile settings

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#5]
# Tasks
- [x] Write POSTMAN tests of server routes
- [x] Write  TestCafe or Playwright tests of user interface (mouse interaction)
- [ ] Write Testcafe or Playwright tests of user interface (keyboard interaction)
