### ISSUE TITLE
As a SpeedScore user, I can view and manage my buddies so that I can connect with other app users

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#50]
# Acceptance Criteria
On "Buddies" mode tab:
- [ ] At the top of the tab, users see a "Search for Buddies" search box to identify potential buddies.
- [ ] As users type into search box, an autocomplete list of possible matches appears in a dropdown list. The list shows profile pictures and display names of the potential matches.
- [ ] String matches are made based on users' email addresses, display names, and real names (real names need to be added to user accounts!)
- [ ] Users can select a potential match and click "Make Buddy Request" to request that person as a buddy. When this happens, 
- [ ] Users see a list of their current buddies and the people who have requested them as a buddy, with a button "Add buddy" next to each request. 
- [ ] Clicking "Add buddy" button (next to a buddy request) adds the person as a buddy. The person who made the request has the user added as a buddy.
- [ ] The user's total number of buddies appears in parentheses following the "Buddies" header.

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] Update database schema to accommodate allow users to have buddies
- [ ] Update database schema to allow user to add real name to account.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
