### ISSUE TITLE
Testing #17: Editing of Data Logged through Live Round Logging UI from "Rounds Mode"

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#51]
This issue writes systematic software tests for #17. 
# To Do
- [ ] Use TestCafe or Playwright to write UI tests for live round logging UI
- [ ] Use Postman to write tests for RESTful API to support live round logging UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
