### ISSUE TITLE
Testing #15: Live Round Logging GUI

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#53]
This issue writes systematic software tests for #15. 
# To Do
- [ ] Use TestCafe or Playwright to write UI tests for live round logging UI
- [ ] Use Postman to write tests for RESTful API to support live round logging UI
- [ ] Create animated GIFs documenting tests results
- [ ] Integrate test results into milestone report
