### ISSUE TITLE
As a user, I can view and edit my round data logged through live round logging UI after the fact, so that I can correct mistakes and undestand my rounds

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#54]
# Acceptance Criteria

- [ ] Rounds logged through live round logging UI appear in "Rounds Table" in "Rounds" mode
- [ ] When users click on "View/Update" button associated with a round logged through live round logging UI, the round is presented in two tabs: "Summary" and "Details". The "Summary" tab is the current view for rounds. The "Details" tab presents the hole-by-hole data in a table (see screenshot) for viewing and editing. 
- [ ] Updates made in either "Summary" or "Details" view are propagated to database

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

## Table of Hole Data in "Details" View
![Snag_26b998cc](https://user-images.githubusercontent.com/27032975/141513868-c919ea7b-bacb-4674-a29b-55ba968a379e.png)

## Viewing/Editing Individual Hole Data in "Details" View
![Snag_26b9bbd5](https://user-images.githubusercontent.com/27032975/141513888-973e17fe-ce8c-4e7a-88f5-efde217e6dce.png)
