### ISSUE TITLE
As a speedgolfer, I can edit my round data through the live round logging GUI so that I can correct mistakes

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#55]
# Acceptance Criteria

From the live round logging GUI:
- [ ] Users can click on "<", ">", and "current hole" buttons to navigate to different holes in current round
- [ ] If data on a hole was already logged, users can edit the data and click "Update" to update data
- [ ] Clicking on "current hole" takes user to logging screen for hole currently being played.
- [ ] From scoring UI, users have side three side menu options: "Scoring instructions," "Round Stats," and "Edit Previous Hole Data" (see screenshot)
- [ ] Through "Scoring Instructions" menu item, users can view scoring instructions (see screenshot)
- [ ] Through "Edit Previous Hole Data" menu item, users can edit previous hole data through a table UI (see screenshots)
- [ ] Through "Round Stats" menu item, users can view round stats (see screenshot)

*Note: Screenshots are meant to convey general look and feel and do not need to be reproduced verbatim! The important point is to use the SpeedScore color theme throughout.

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] Update database schema for rounds to accommodate the additional data
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage
...
## Menu items available in round logging GUI
![Snag_26a81dc3](https://user-images.githubusercontent.com/27032975/141511468-f3df064e-ac6a-4149-be66-dbe3e50c9787.png)

## Scoring Instructions page
![Snag_26b1d688](https://user-images.githubusercontent.com/27032975/141512802-1a5a478e-fad4-49c0-a45c-8ea8a872fa34.png)

## Hole Data Editing UI: Main Table
![Snag_26b11172](https://user-images.githubusercontent.com/27032975/141512702-3d401823-53c5-49cf-af72-3378935b7609.png)

## Hole Data Editing UI: Individual Hole
![Snag_26b17d4c](https://user-images.githubusercontent.com/27032975/141512755-aaa1bd20-d574-4e2b-926b-d71db76cef5f.png)

## Round stats page
![Snag_26b21045](https://user-images.githubusercontent.com/27032975/141512829-35715c79-8ff8-4cf2-8982-caf21cc08125.png)
