### ISSUE TITLE
As a user, I can log a round "live" by clicking buttons, so that I can capture detailed data on my round

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#56]
# Acceptance Criteria
- [ ] When user clicks "Log Round," they are given choices "Track Live (GUI)" or "Log Previously Played"
- [ ] If user chooses "Track Live (GUI)" they are taken to the Live Tracking GUI.
- [ ] Users click on "Start Round" button to start round
- [ ] Users click on "Ball in Hole" to finish hole; time for hole auto-recorded
- [ ] Users can use arrow buttons to adjust hole score after "Ball in Hole" clicked (default is par for hole)
- [ ] GUI moves to next hole after previous hole is completed, with "Ball in Hole" button shown

*Screenshots attached to this user story provide further details*

# Implementation Todos

Front end:

- [ ] First thing that must be done in the front end code.
- [ ] Second thing that must be done in the front end code.
...

Back end:

- [ ] First thing that must be done in the back end code.
- [ ] Second thing that must be done in the back end code.
...

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

## Starting screen for live logging GUI
![Snag_268eec4c](https://user-images.githubusercontent.com/27032975/141507824-d8a8af96-ad1d-4d09-9ee0-247f0bee3d74.png)
## After user clicks "Start Round Timer"
![Snag_268f2175](https://user-images.githubusercontent.com/27032975/141507848-b4d4d91d-5a63-46d3-ba61-ea09815eb6a8.png)

## Hole logging GUI
![Snag_268f379d](https://user-images.githubusercontent.com/27032975/141507857-d5566d77-4614-4c20-9d0b-4794818a0586.png)

## After user clicks "Click when in Hole" button to score a hole
![Snag_268f4f8a](https://user-images.githubusercontent.com/27032975/141507875-8690a538-d91b-403e-ba9e-2255ba16ec62.png)
