### ISSUE TITLE
Testing: As a user, I can delete a speedgolf round

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#6]
# Tasks
- [ ] Write POSTMAN tests for delete route
- [ ] Write TestCafe or Playwright tests for delete UI (mouse interaction)
- [ ] Write TestCafe or Playwright tests for delete UI (keyboard interaction)
