### ISSUE TITLE
Testing: As a user, I can update a speedgolf round

### ISSUE THREAD

**Issue by ahsun-tariq** [wsu-cpts489-fa21/tp-good-team#7]
# Tasks
- [ ] Write POSTMAN tests for update route
- [ ] Write TestCafe/Playwright tests for update UI (mouse interaction)
- [ ] Write TestCafe/Playwright tests for update UI (keyboardinteraction)
- [ ] Record animation GIFS of test results
